-- Bucks Global (Hybrid) schema for Supabase/Postgres
-- IPFS stores the content (CID); Postgres stores metadata + social graph.

create table if not exists public.users (
  peer_id text primary key,
  username text,
  handle text,
  avatar text,
  banner text,
  bio text,
  location text,
  did text,
  secret_key text,
  dag_root text
);

create table if not exists public.posts (
  id text primary key,
  name text,
  description text,
  filename text,
  type text,
  author text,
  avatar text,
  timestamp text,
  peer_id text,
  size bigint,
  is_pinned smallint default 0,
  content text,
  visibility text,
  original_cid text,
  tag text
);

create index if not exists idx_posts_name on public.posts (name);
create index if not exists idx_posts_description on public.posts (description);

create table if not exists public.interactions (
  id bigint generated by default as identity primary key,
  post_cid text references public.posts (id) on delete cascade,
  user_peer_id text,
  type text,
  timestamp text
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_cid text references public.posts (id) on delete cascade,
  user_peer_id text,
  username text,
  text text,
  timestamp text
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_peer_id text,
  receiver_peer_id text,
  text text,
  timestamp text,
  cid text,
  is_read smallint default 0,
  filename text,
  mime_type text
);

create table if not exists public.guardians (
  user_peer_id text,
  guardian_peer_id text,
  primary key (user_peer_id, guardian_peer_id)
);

create table if not exists public.recovery_requests (
  id bigint generated by default as identity primary key,
  old_peer_id text,
  new_peer_id text,
  timestamp text,
  status text default 'pending'
);

create table if not exists public.recovery_approvals (
  request_id bigint,
  guardian_peer_id text,
  primary key (request_id, guardian_peer_id)
);

create table if not exists public.following (
  user_peer_id text,
  following_peer_id text,
  relationship_type text default 'following',
  timestamp text,
  library_cid text,
  vouched_cid text,
  last_synced text,
  username text,
  primary key (user_peer_id, following_peer_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_peer_id text,
  type text,
  title text,
  message text,
  link text,
  timestamp text,
  is_read smallint default 0
);

create table if not exists public.discovered_peers (
  peer_id text primary key,
  username text,
  avatar text,
  dag_root text,
  last_seen text,
  discovery_type text
);

