-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: add uuid7 to users, add connections / following /
--            notifications / discovered_peers tables
-- Safe to run multiple times (all statements are idempotent).
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Add uuid7 column to existing users table (no-op if already present)
alter table if exists public.users
  add column if not exists uuid7 text;

create index if not exists idx_users_uuid7 on public.users (uuid7);

-- 2. Connections (mutual-sync pairs used for the messaging system)
create table if not exists public.connections (
  from_uuid7  text not null,
  to_uuid7    text not null,
  synced_at   text,
  primary key (from_uuid7, to_uuid7)
);

create index if not exists idx_connections_from on public.connections (from_uuid7);
create index if not exists idx_connections_to   on public.connections (to_uuid7);

-- 3. Following / social graph
create table if not exists public.following (
  user_peer_id      text not null,
  following_peer_id text not null,
  relationship_type text default 'following',
  timestamp         text,
  library_cid       text,
  vouched_cid       text,
  last_synced       text,
  username          text,
  primary key (user_peer_id, following_peer_id)
);

create index if not exists idx_following_user   on public.following (user_peer_id);
create index if not exists idx_following_target on public.following (following_peer_id);

-- 4. In-app notifications
create table if not exists public.notifications (
  id           bigint generated by default as identity primary key,
  user_peer_id text,
  type         text,
  title        text,
  message      text,
  link         text,
  timestamp    text,
  is_read      smallint default 0
);

create index if not exists idx_notifications_user on public.notifications (user_peer_id);

-- 5. Peer discovery cache
create table if not exists public.discovered_peers (
  peer_id        text primary key,
  username       text,
  avatar         text,
  dag_root       text,
  last_seen      text,
  discovery_type text
);

-- 6. Back-fill uuid7 index on users in case the column existed without index
create index if not exists idx_users_uuid7 on public.users (uuid7);
